version: '3.8'

services:
  backend:
    image: ${{ secrets.DOCKER_USERNAME }}/my-app:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db

  frontend:
    image: ${{ secrets.DOCKER_USERNAME }}/my-app:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-data-prod:
    driver: local